'use strict';
const fs=require('fs');
const assert=require('assert');
const taxonomy=fs.readFileSync('fixes/area-taxonomy-v1.js','utf8');
const taskControls=fs.readFileSync('fixes/task-delete-controls-v1.js','utf8');
const homeFilters=fs.readFileSync('fixes/home-area-filters-v1.js','utf8');
const taskEnd=fs.readFileSync('fixes/task-end-time-v1.js','utf8');
assert(taxonomy.includes("area==='professional'"));
assert(taxonomy.includes("area==='education'"));
assert(taxonomy.includes("area==='personal'"));
assert(taxonomy.includes("source==='leisure'"));
assert(taxonomy.includes("isHealthTask(task)||isLeisureTask(task)||sphere==='personal'"));
assert(taskControls.includes('Профессиональное'));
assert(taskControls.includes('Образовательное'));
assert(taskControls.includes('Личное'));
assert(!taskControls.includes('<option value="health">Здоровье</option>'));
assert(homeFilters.includes('<option value="professional">Профессиональное</option>'));
assert(homeFilters.includes('<option value="education">Образовательное</option>'));
assert(homeFilters.includes('<option value="personal">Личное</option>'));
assert(taskEnd.includes("['professional','Профессиональное']"));
assert(taskEnd.includes("['education','Образовательное']"));
assert(taskEnd.includes("['personal','Личное']"));
console.log('area taxonomy regression: ok');
