'use strict';
const fs=require('fs');
const assert=require('assert');
const js=fs.readFileSync('fixes/education-collapse-fix-v1.js','utf8');
const css=fs.readFileSync('styles/education-cards-v1.css','utf8');
const html=fs.readFileSync('index.html','utf8');

assert(js.includes('[data-add-life="education"]'),'education cards must be detected from actual renderLife markup');
assert(js.includes("return card.querySelector('[data-add-life=\"education\"]')?.dataset.lifeKey||''"),'collapse state must use stable lifeKey instead of heading text');
assert(js.includes("content.addEventListener('click'"),'collapse actions must use one delegated click handler');
assert(js.includes('setCollapsed(card,!isCollapsed(card))'),'individual toggle must invert only its own category');
assert(js.includes('data-education-collapse-all'),'collapse-all control is missing');
assert(js.includes('data-education-expand-all'),'expand-all control is missing');
assert(js.includes("const STORAGE_KEY='educationCollapseState.v2'"),'stale collapse state must be reset with versioned storage');
assert(js.includes('sessionStorage.setItem(STORAGE_KEY'),'collapse state must survive re-render in the current session');
assert(js.includes('body.hidden=collapsed'),'native hidden state must follow category collapse state');
assert(js.includes("hero.querySelector('.education-global-collapse-controls')"),'global controls must be anchored in the Education hero');
assert(css.includes('.education-category-collapsed > .education-category-body'),'collapsed state must be enforced by card class');
assert(css.includes('display: none !important'),'collapsed body must remain hidden even if other education decorators run');
assert(css.includes('.hero .education-global-collapse-controls'),'global controls need explicit visible hero styling');
assert(css.includes('max-height: 640px'),'expanded categories must have bounded height');
assert(css.includes('overflow-y: auto'),'expanded categories must scroll internally');
assert(html.includes('styles/education-cards-v1.css?v=4'),'Education CSS cache bust is missing');
assert(html.includes('fixes/education-collapse-fix-v1.js?v=5'),'Education collapse JS cache bust is missing');
console.log('education category collapse v5 stable: ok');
