'use strict';
const fs=require('fs');
const assert=require('assert');
const css=fs.readFileSync('styles/education-cards-v1.css','utf8');
const js=fs.readFileSync('fixes/education-collapse-fix-v1.js','utf8');
const html=fs.readFileSync('index.html','utf8');
assert(css.includes('::-webkit-scrollbar-thumb'),'education scrollbars need an explicit native thumb style');
assert(css.includes('scrollbar-color: #8f7cff #eef0f7'),'education scrollbars need explicit cross-browser colors');
assert(css.includes('.education-category-static-thumb::after'),'short education categories need a deterministic blue visual thumb');
assert(css.includes('background: #8f7cff'),'static education thumb must use the blue accent');
assert(js.includes('syncScrollbarIndicator'),'short education categories must be measured after render');
assert(js.includes('body.scrollHeight>body.clientHeight+1'),'native overflow must be detected before applying the static thumb');
assert(js.includes("body.classList.toggle('education-category-static-thumb',!hasNativeOverflow)"),'short categories must receive the static thumb class');
assert(html.includes('styles/education-cards-v1.css?v=7'),'education CSS cache bust must be 7');
assert(html.includes('fixes/education-collapse-fix-v1.js?v=7'),'education collapse JS cache bust must be 7');
console.log('education visible scrollbar all categories: ok');
