'use strict';
const fs=require('fs');
const assert=require('assert');
const js=fs.readFileSync('fixes/home-area-filters-v1.js','utf8');
const css=fs.readFileSync('styles/home-area-filters-v1.css','utf8');
const html=fs.readFileSync('index.html','utf8');
assert(js.includes('data-home-area-filter'),'home area filter controls are missing');
assert(js.includes('<option value="professional">Профессиональное</option>'),'professional option is missing');
assert(js.includes('<option value="education">Образовательное</option>'),'education option is missing');
assert(js.includes('<option value="personal">Личное</option>'),'personal option is missing');
assert(js.includes('<option value="all">Показать все</option>'),'show-all option is missing');
assert(js.includes("kind==='focus'"),'focus card filter is missing');
assert(js.includes('overdueFilter')&&js.includes('.home-overdue-card'),'overdue card filter is missing');
assert(css.includes('.home-area-filter'),'home filter styles are missing');
assert(html.includes('fixes/area-taxonomy-v1.js?v=1'),'area taxonomy script is not loaded');
assert(html.includes('fixes/home-area-filters-v1.js?v=2'),'home filter script is not loaded');
assert(html.includes('styles/home-area-filters-v1.css?v=1'),'home filter stylesheet is not loaded');
console.log('home area filters: ok');
