'use strict';
const fs=require('fs');
const assert=require('assert');
const js=fs.readFileSync('fixes/task-delete-controls-v1.js','utf8');
const css=fs.readFileSync('styles/task-delete-controls-v1.css','utf8');
assert(js.includes("button.textContent='Удалить'"),'single delete button is missing');
assert(js.includes("button.textContent='Удалить всё'"),'bulk delete button is missing');
assert(js.includes('dismissedLinkedTaskKeys'),'linked task dismiss registry is missing');
assert(js.includes('rememberDismissedLinkedTask'),'linked task dismissal is missing');
assert(js.includes('purgeDismissedLinkedTasks'),'dismissed linked tasks must not reappear');
assert(js.includes("Источник задачи сохранится; удаляется только карточка из списка задач."),'linked task delete warning is missing');
assert(js.includes('habit.skippedDates'),'generated health occurrences must remember skipped dates');
assert(js.includes('purgeSkippedHealthTasks'),'skipped health occurrences must not reappear after regeneration');
assert(js.includes("group.querySelectorAll('.list-row:not([hidden])')"),'list bulk delete must use only visible task rows');
assert(js.includes("workspace.querySelectorAll('.task-group').forEach(addListGroupDeleteAll)"),'every list group must receive bulk delete');
assert(js.includes('dataset.deleteListGroup'),'list group bulk delete control is missing');
assert(js.includes('deleteMany(visibleTasksInGroup(group)'),'list group bulk delete handler is missing');
assert(js.includes('visibleTasksInKanbanColumn(col)'),'kanban bulk delete must respect visible cards');
assert(js.includes('dataset.deleteKanbanColumn'),'kanban bulk delete control is missing');
assert(js.includes('deleteMany(visibleTasksInKanbanColumn(col)'),'kanban bulk delete handler is missing');
assert(js.includes('<option value="professional">Профессиональное</option>'),'professional category filter is missing');
assert(js.includes('<option value="education">Образовательное</option>'),'education category filter is missing');
assert(js.includes('<option value="personal">Личное</option>'),'personal category filter is missing');
assert(js.includes('taskMatchesCanonicalArea'),'task filter must use shared canonical taxonomy');
assert(js.includes('Здоровье и досуг относятся к «Личному»'),'personal grouping explanation is missing');
assert(js.includes('data-task-source-explanation'),'task source explanation is missing');
assert(js.includes("BLOCKED_ROUTINE_TITLES=['ходьба','вода','капли в глаза']"),'requested routine cleanup list is missing');
assert(js.includes("workspace.querySelectorAll('.kanban-card')"),'kanban delete decoration is missing');
assert(css.includes('[data-delete-list-group]'),'list bulk delete layout rule is missing');
assert(css.includes('[data-delete-kanban-column]'),'kanban bulk delete layout rule is missing');
assert(css.includes('.kanban-actions'),'kanban action layout rule is missing');
console.log('task delete controls: ok');
