'use strict';
const fs=require('fs');
const assert=require('assert');
const js=fs.readFileSync('fixes/task-end-time-v1.js','utf8');
const html=fs.readFileSync('index.html','utf8');
assert(js.includes("label:'Дата начала'"),'start-date field is missing');
assert(js.includes("label:'Дата окончания'"),'end-date field is missing');
assert(js.includes("label:'Время окончания'"),'end-time field is missing');
assert(!js.includes("label:'Минуты'"),'minutes field must not be shown');
assert(js.includes("if(!o.endDate)o.endDate=o.date"),'end date must default to start date on save');
assert(js.includes("if(!endDateEdited)endDate.value=startDate.value"),'untouched end date must follow start date');
assert(js.includes("if(o.date&&o.endDate&&o.endDate<o.date)"),'date range validation is missing');
assert(js.includes("if(start!==null&&end!==null&&end<start)"),'daily time range validation is missing');
assert(js.includes('task-daily-schedule'),'multi-day schedule editor must be rendered');
assert(js.includes('o.dailySchedule=scheduleResult.schedule'),'daily schedule must be persisted on the task');
assert(js.includes("o.duration=start!==null&&end!==null?end-start"),'default daily duration compatibility calculation is missing');
assert(js.includes('derivedEnd'),'existing task end-time derivation is missing');
assert(js.includes("['professional','Профессиональное']"),'professional sphere label is missing');
assert(js.includes("['education','Образовательное']"),'education sphere label is missing');
assert(js.includes("['personal','Личное']"),'personal sphere label is missing');
assert(html.includes('fixes/task-calendar-range-v1.js?v=1'),'task calendar range model must load before the editor');
assert(html.includes('fixes/task-end-time-v1.js?v=3'),'task end-time fix cache version is missing');
assert(html.indexOf('fixes/task-calendar-range-v1.js?v=1')<html.indexOf('fixes/task-end-time-v1.js?v=3'),'range helper must load before task editor');
console.log('task date range, daily schedule and end time: ok');
