'use strict';
const fs=require('fs');
const assert=require('assert');
const js=fs.readFileSync('fixes/task-delete-controls-v1.js','utf8');
const css=fs.readFileSync('styles/task-delete-controls-v1.css','utf8');
assert(js.includes("button.textContent='Удалить'"),'single delete button is missing');
assert(js.includes("button.textContent='Удалить всё'"),'bulk delete button is missing');
assert(js.includes('task.generatedLinked'),'linked tasks must be protected from direct deletion');
assert(js.includes('habit.skippedDates'),'generated health occurrences must remember skipped dates');
assert(js.includes('purgeSkippedHealthTasks'),'skipped health occurrences must not reappear after regeneration');
assert(js.includes('visibleTasksInGroup(group)'),'bulk delete must respect the tasks currently shown in the Later group');
assert(js.includes('visibleTasksInKanbanColumn(col)'),'kanban bulk delete must respect visible cards');
assert(js.includes('dataDeleteKanbanColumn'),'kanban bulk delete control is missing');
assert(js.includes('deleteMany(visibleTasksInKanbanColumn(col)'),'kanban bulk delete handler is missing');
assert(js.includes("<option value=\"projects\">По проектам</option>"),'projects category filter is missing');
assert(js.includes("<option value=\"education\">Образование</option>"),'education category filter is missing');
assert(js.includes("<option value=\"health\">Здоровье</option>"),'health category filter is missing');
assert(js.includes("BLOCKED_ROUTINE_TITLES=['ходьба','вода','капли в глаза']"),'requested routine cleanup list is missing');
assert(js.includes("workspace.querySelectorAll('.kanban-card')"),'kanban delete decoration is missing');
assert(css.includes('[data-delete-later-tasks]'),'bulk delete layout rule is missing');
assert(css.includes('[data-delete-kanban-column]'),'kanban bulk delete layout rule is missing');
assert(css.includes('.kanban-actions'),'kanban action layout rule is missing');
console.log('task delete controls: ok');
