'use strict';
const fs=require('fs');
const assert=require('assert');
const js=fs.readFileSync('fixes/week-summary-list-v1.js','utf8');
const css=fs.readFileSync('styles/week-summary-list-v1.css','utf8');
const html=fs.readFileSync('index.html','utf8');
assert(js.includes("const filters=['all','open','done','priority']"),'week summary filters are missing');
assert(js.includes('data-week-summary-filter'),'week summary controls are not decorated');
assert(js.includes("labels={all:'Все задачи недели'"),'week list labels are missing');
assert(js.includes("filter==='open'?!task.done"),'open task filter is missing');
assert(js.includes("filter==='done'?task.done"),'done task filter is missing');
assert(js.includes("task.priority==='priority'||task.priority==='urgent'"),'priority filter must include priority and urgent tasks');
assert(js.includes('data-week-list-close'),'week list close control is missing');
assert(js.includes('data-week-list-add'),'week list add control is missing');
assert(js.includes('data-week-list-edit'),'week list edit control is missing');
assert(js.includes('data-week-list-done'),'week list completion control is missing');
assert(js.includes("openTask(null,{date:add.dataset.date||bounds()[0]"),'week list add must open task editor with week date');
assert(js.includes("task.status=task.done?'done':'planned'"),'week list completion must sync status');
assert(css.includes('.week-summary>[data-week-summary-filter]'),'week summary needs clickable styling');
assert(css.includes('.week-summary-list-body'),'week list body styling is missing');
assert(html.includes('styles/week-summary-list-v1.css?v=1'),'week summary CSS asset is not loaded');
assert(html.includes('fixes/week-summary-list-v1.js?v=1'),'week summary JS asset is not loaded');
console.log('week summary list: ok');
